theme: jekyll-theme-slate
title: Andy Horner
description: Software developer. Travel hacker. Technology enthusiast.

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"